name: Build and Publish NuGet

on:
  push:
    tags:
      - 'v*.*.*'   # Trigger on version tags like v1.0.0
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore Friday/Friday.csproj

    - name: Build
      run: dotnet build Friday/Friday.csproj --configuration Release --no-restore

    - name: Read and increment version
      id: version
      shell: bash
      run: |
        VERSION_FILE="Friday/VERSION"
        VERSION=$(cat $VERSION_FILE)
        echo "Current version: $VERSION"
        # Increment patch version
        IFS='.' read -r major minor patch <<< "$VERSION"
        patch=$((patch+1))
        NEW_VERSION="$major.$minor.$patch"
        echo $NEW_VERSION > $VERSION_FILE
        echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
    - name: Pack NuGet package
      run: dotnet pack Friday/Friday.csproj --configuration Release --no-build --output Friday/nupkg /p:PackageVersion=${{ steps.version.outputs.new_version }}

    - name: Publish NuGet package
      run: dotnet nuget push Friday/nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate